name: "sample"
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build stage
        run: echo "this is my first step"
  stage:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: deploy stage
        run: echo "deploy to stage"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: deploy stagg
        run: echo "deploy to dev"
  
  
  
    
