name: "sample"
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build step
        run: echo "this is my first step"

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy stage
        run: echo "deploy to dev"
  
  
  
    
