# who has triggered the workflow
# https://docs.github.com/en/actions/reference/workflows-and-actions/contexts#github-context
name: Context variables demo
on: workflow_dispatch
jobs:
  context-demo:
    runs-on: ubuntu-latest
    steps:
      - name: Use context variables
        run: |
          echo "This workflow is triggered by ${{ github.actor }}"
          echo "The repository name is ${{ github.repository }}"
          echo "The branch is ${{ github.ref_name }}"

      - name: Print all variables under github
        run: echo "${{ toJson(github) }}"

      - name: Print environment variables
        run: printenv
        # get latest commit id
        run: echo "$GITHUB_SHA"
